-- MySQL Script generated by MySQL Workbench
-- Thu May  2 10:25:06 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Food Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Food Category` (
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ingredients` (
  `name` VARCHAR(50) NOT NULL,
  `caloriesper100grams` INT NOT NULL,
  `Food Category_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`name`),
  INDEX `fk_Ingredients_Food Category1_idx` (`Food Category_name` ASC) VISIBLE,
  CONSTRAINT `fk_Ingredients_Food Category1`
    FOREIGN KEY (`Food Category_name`)
    REFERENCES `mydb`.`Food Category` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`National Cuisine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`National Cuisine` (
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recipies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recipies` (
  `difficulty` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `tip_1` VARCHAR(200) NULL,
  `preparation_time` INT NOT NULL,
  `cooking_time` INT ZEROFILL NOT NULL,
  `tip_2` VARCHAR(200) NULL,
  `tip_3` VARCHAR(200) NULL,
  `fat` INT NULL,
  `protein` INT NULL,
  `carbs` INT NULL,
  `cooking/pastry` TINYINT NULL COMMENT 'Cooking->0\nPastry->1',
  `basic_ingredient_name` VARCHAR(50) NOT NULL,
  `National Cuisine_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`name`),
  INDEX `fk_Recipies_Ingredients1_idx` (`basic_ingredient_name` ASC) VISIBLE,
  INDEX `fk_Recipies_National Cuisine1_idx` (`National Cuisine_name` ASC) VISIBLE,
  CONSTRAINT `fk_Recipies_Ingredients1`
    FOREIGN KEY (`basic_ingredient_name`)
    REFERENCES `mydb`.`Ingredients` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recipies_National Cuisine1`
    FOREIGN KEY (`National Cuisine_name`)
    REFERENCES `mydb`.`National Cuisine` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipment` (
  `name` VARCHAR(50) NOT NULL,
  `manual` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recipies_has_Equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recipies_has_Equipment` (
  `Recipies_name` VARCHAR(50) NOT NULL,
  `Equipment_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Recipies_name`, `Equipment_name`),
  INDEX `fk_Recipies_has_Equipment_Equipment1_idx` (`Equipment_name` ASC) VISIBLE,
  INDEX `fk_Recipies_has_Equipment_Recipies_idx` (`Recipies_name` ASC) VISIBLE,
  CONSTRAINT `fk_Recipies_has_Equipment_Recipies`
    FOREIGN KEY (`Recipies_name`)
    REFERENCES `mydb`.`Recipies` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recipies_has_Equipment_Equipment1`
    FOREIGN KEY (`Equipment_name`)
    REFERENCES `mydb`.`Equipment` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recipies_has_Ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recipies_has_Ingredients` (
  `Recipies_name` VARCHAR(50) NOT NULL,
  `Ingredients_name` VARCHAR(50) NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`Recipies_name`, `Ingredients_name`),
  INDEX `fk_Recipies_has_Ingredients_Ingredients1_idx` (`Ingredients_name` ASC) VISIBLE,
  INDEX `fk_Recipies_has_Ingredients_Recipies1_idx` (`Recipies_name` ASC) VISIBLE,
  CONSTRAINT `fk_Recipies_has_Ingredients_Recipies1`
    FOREIGN KEY (`Recipies_name`)
    REFERENCES `mydb`.`Recipies` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recipies_has_Ingredients_Ingredients1`
    FOREIGN KEY (`Ingredients_name`)
    REFERENCES `mydb`.`Ingredients` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Steps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Steps` (
  `Step_Description` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`Step_Description`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recipies_has_Steps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recipies_has_Steps` (
  `Recipies_name` VARCHAR(50) NOT NULL,
  `Steps_Step_Description` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`Recipies_name`, `Steps_Step_Description`),
  INDEX `fk_Recipies_has_Steps_Steps1_idx` (`Steps_Step_Description` ASC) VISIBLE,
  INDEX `fk_Recipies_has_Steps_Recipies1_idx` (`Recipies_name` ASC) VISIBLE,
  CONSTRAINT `fk_Recipies_has_Steps_Recipies1`
    FOREIGN KEY (`Recipies_name`)
    REFERENCES `mydb`.`Recipies` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recipies_has_Steps_Steps1`
    FOREIGN KEY (`Steps_Step_Description`)
    REFERENCES `mydb`.`Steps` (`Step_Description`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Meal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Meal` (
  `Meal_Form` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Meal_Form`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Meal_has_Recipies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Meal_has_Recipies` (
  `Meal_Meal_Form` VARCHAR(50) NULL,
  `Recipies_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Meal_Meal_Form`, `Recipies_name`),
  INDEX `fk_Meal_has_Recipies_Recipies1_idx` (`Recipies_name` ASC) VISIBLE,
  INDEX `fk_Meal_has_Recipies_Meal1_idx` (`Meal_Meal_Form` ASC) VISIBLE,
  CONSTRAINT `fk_Meal_has_Recipies_Meal1`
    FOREIGN KEY (`Meal_Meal_Form`)
    REFERENCES `mydb`.`Meal` (`Meal_Form`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Meal_has_Recipies_Recipies1`
    FOREIGN KEY (`Recipies_name`)
    REFERENCES `mydb`.`Recipies` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Etiquette`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Etiquette` (
  `Meal_Type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Meal_Type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recipies_has_Etiquette`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recipies_has_Etiquette` (
  `Recipies_name` VARCHAR(50) NOT NULL,
  `Etiquette_Meal_Type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Recipies_name`, `Etiquette_Meal_Type`),
  INDEX `fk_Recipies_has_Etiquette_Etiquette1_idx` (`Etiquette_Meal_Type` ASC) VISIBLE,
  INDEX `fk_Recipies_has_Etiquette_Recipies1_idx` (`Recipies_name` ASC) VISIBLE,
  CONSTRAINT `fk_Recipies_has_Etiquette_Recipies1`
    FOREIGN KEY (`Recipies_name`)
    REFERENCES `mydb`.`Recipies` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recipies_has_Etiquette_Etiquette1`
    FOREIGN KEY (`Etiquette_Meal_Type`)
    REFERENCES `mydb`.`Etiquette` (`Meal_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Thematic Unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Thematic Unit` (
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(200) NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recipies_has_Thematic Unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recipies_has_Thematic Unit` (
  `Recipies_name` VARCHAR(50) NOT NULL,
  `Thematic Unit_name` VARCHAR(50) NULL,
  PRIMARY KEY (`Recipies_name`, `Thematic Unit_name`),
  INDEX `fk_Recipies_has_Thematic Unit_Thematic Unit1_idx` (`Thematic Unit_name` ASC) VISIBLE,
  INDEX `fk_Recipies_has_Thematic Unit_Recipies1_idx` (`Recipies_name` ASC) VISIBLE,
  CONSTRAINT `fk_Recipies_has_Thematic Unit_Recipies1`
    FOREIGN KEY (`Recipies_name`)
    REFERENCES `mydb`.`Recipies` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recipies_has_Thematic Unit_Thematic Unit1`
    FOREIGN KEY (`Thematic Unit_name`)
    REFERENCES `mydb`.`Thematic Unit` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professional Expertise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professional Expertise` (
  `type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cook` (
  `name` VARCHAR(50) NOT NULL,
  `surname` VARCHAR(50) NOT NULL,
  `phone_number` INT NOT NULL,
  `Date_of_birth` DATE NOT NULL,
  `years_of_experience` INT NOT NULL,
  `Professional Expertise_type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`name`, `surname`),
  INDEX `fk_Cook_Professional Expertise1_idx` (`Professional Expertise_type` ASC) VISIBLE,
  CONSTRAINT `fk_Cook_Professional Expertise1`
    FOREIGN KEY (`Professional Expertise_type`)
    REFERENCES `mydb`.`Professional Expertise` (`type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Has_specialisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Has_specialisation` (
  `National Cuisine_name` VARCHAR(50) NOT NULL,
  `Cook_name` VARCHAR(50) NOT NULL,
  `Cook_surname` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`National Cuisine_name`, `Cook_name`, `Cook_surname`),
  INDEX `fk_National Cuisine_has_Cook_Cook1_idx` (`Cook_name` ASC, `Cook_surname` ASC) VISIBLE,
  INDEX `fk_National Cuisine_has_Cook_National Cuisine1_idx` (`National Cuisine_name` ASC) VISIBLE,
  CONSTRAINT `fk_National Cuisine_has_Cook_National Cuisine1`
    FOREIGN KEY (`National Cuisine_name`)
    REFERENCES `mydb`.`National Cuisine` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_National Cuisine_has_Cook_Cook1`
    FOREIGN KEY (`Cook_name` , `Cook_surname`)
    REFERENCES `mydb`.`Cook` (`name` , `surname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Episode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Episode` (
  `episode_number` INT NOT NULL,
  PRIMARY KEY (`episode_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Judges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Judges` (
  `Cook_name` VARCHAR(50) NOT NULL,
  `Cook_surname` VARCHAR(50) NOT NULL,
  `Episode_episode_number` INT NOT NULL,
  PRIMARY KEY (`Cook_name`, `Cook_surname`, `Episode_episode_number`),
  INDEX `fk_Cook_has_Episode_Episode1_idx` (`Episode_episode_number` ASC) VISIBLE,
  INDEX `fk_Cook_has_Episode_Cook1_idx` (`Cook_name` ASC, `Cook_surname` ASC) VISIBLE,
  CONSTRAINT `fk_Cook_has_Episode_Cook1`
    FOREIGN KEY (`Cook_name` , `Cook_surname`)
    REFERENCES `mydb`.`Cook` (`name` , `surname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cook_has_Episode_Episode1`
    FOREIGN KEY (`Episode_episode_number`)
    REFERENCES `mydb`.`Episode` (`episode_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`asssignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`asssignment` (
  `Cook_name` VARCHAR(50) NOT NULL,
  `Cook_surname` VARCHAR(50) NOT NULL,
  `Episode_episode_number` INT NOT NULL,
  `National Cuisine_name` VARCHAR(50) NOT NULL,
  `Recipies_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Cook_name`, `Cook_surname`, `Episode_episode_number`, `National Cuisine_name`, `Recipies_name`),
  INDEX `fk_asssignment_Episode1_idx` (`Episode_episode_number` ASC) VISIBLE,
  INDEX `fk_asssignment_National Cuisine1_idx` (`National Cuisine_name` ASC) VISIBLE,
  INDEX `fk_asssignment_Recipies1_idx` (`Recipies_name` ASC) VISIBLE,
  CONSTRAINT `fk_asssignment_Cook1`
    FOREIGN KEY (`Cook_name` , `Cook_surname`)
    REFERENCES `mydb`.`Cook` (`name` , `surname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asssignment_Episode1`
    FOREIGN KEY (`Episode_episode_number`)
    REFERENCES `mydb`.`Episode` (`episode_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asssignment_National Cuisine1`
    FOREIGN KEY (`National Cuisine_name`)
    REFERENCES `mydb`.`National Cuisine` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asssignment_Recipies1`
    FOREIGN KEY (`Recipies_name`)
    REFERENCES `mydb`.`Recipies` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`eval_for`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`eval_for` (
  `asssignment_Cook_name` VARCHAR(50) NOT NULL,
  `asssignment_Cook_surname` VARCHAR(50) NOT NULL,
  `asssignment_Episode_episode_number` INT NOT NULL,
  `asssignment_National Cuisine_name` VARCHAR(50) NOT NULL,
  `asssignment_Recipies_name` VARCHAR(50) NOT NULL,
  `Judges_Cook_name` VARCHAR(50) NOT NULL,
  `Judges_Cook_surname` VARCHAR(50) NOT NULL,
  `Judges_Episode_episode_number` INT NOT NULL,
  `evaluation` INT NOT NULL,
  PRIMARY KEY (`asssignment_Cook_name`, `asssignment_Cook_surname`, `asssignment_Episode_episode_number`, `asssignment_National Cuisine_name`, `asssignment_Recipies_name`, `Judges_Cook_name`, `Judges_Cook_surname`, `Judges_Episode_episode_number`),
  INDEX `fk_asssignment_has_Judges_Judges1_idx` (`Judges_Cook_name` ASC, `Judges_Cook_surname` ASC, `Judges_Episode_episode_number` ASC) VISIBLE,
  INDEX `fk_asssignment_has_Judges_asssignment1_idx` (`asssignment_Cook_name` ASC, `asssignment_Cook_surname` ASC, `asssignment_Episode_episode_number` ASC, `asssignment_National Cuisine_name` ASC, `asssignment_Recipies_name` ASC) VISIBLE,
  CONSTRAINT `fk_asssignment_has_Judges_asssignment1`
    FOREIGN KEY (`asssignment_Cook_name` , `asssignment_Cook_surname` , `asssignment_Episode_episode_number` , `asssignment_National Cuisine_name` , `asssignment_Recipies_name`)
    REFERENCES `mydb`.`asssignment` (`Cook_name` , `Cook_surname` , `Episode_episode_number` , `National Cuisine_name` , `Recipies_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asssignment_has_Judges_Judges1`
    FOREIGN KEY (`Judges_Cook_name` , `Judges_Cook_surname` , `Judges_Episode_episode_number`)
    REFERENCES `mydb`.`Judges` (`Cook_name` , `Cook_surname` , `Episode_episode_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
